version: "3.5"
services:
  server:
    container_name: server
    build: . # Dockerfile이 위치한 경로
    ports:
      - "8000:8000"
      - "8001:8001"
      - "50022:22"
    #environment: # 환경변수 설정
    #  - NODE_PATH=src
    #  - DB_HOST=mongo
    #  - DB=test
    networks: # 각 컨테이너를 연결하는 네트워크
      - backend

    volumes:
      - ./tmp:/tmp/

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      - backend
               
    volumes:
      - ./tmp:/tmp/
 
networks:
  backend:
    driver: bridge

